### ISSUE TITLE
Confusion about cross-distortion types

### ISSUE THREAD

**Issue by chensming** [lixinustc/Casual-IR-DIL#3]
Hi, you have done a nice job and I am interested in it. When refer to "for cross-distortion types, DILps achieves better performance for RealSR and Image Deraining", I'm confused as to why a different dataset is a different degenerate type (eg. raining datasets).

**Comment by lixinustc** [comment]
Thanks for your questions. For deraining, the ways of producing the rain in different datasets are different, such as rain stick or raindrops, dense or sparse rain, etc.

**Comment by chensming** [comment]
> Thanks for your questions. For deraining, the ways of producing the rain in different datasets are different, such as rain stick or raindrops, dense or sparse rain, etc.

I see. thanks, bro.
